import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import LenisSmoothScroll from "@/components/LenisScroll";
import Loader from "@/components/UI/Loader";
import Token3d from "@/components/UI/Token3D";

const Font1 = localFont({
  src: [
    { path: "./fonts/LexendHM-bold.ttf", weight: "300", style: "normal" },
  ],
  variable: '--font-body',
  display: "swap",
  fallback: ["system-ui, sans-serif"],
})

const Font2 = localFont({
  src: [
    { path: "./fonts/LexendHM-Regular.ttf", weight: "400", style: "normal" },
  ],
  variable: '--font-display',
  display: "swap",
  fallback: ["system-ui, sans-serif"],
})

export const metadata = {
  title: "Heidelberg Materials - Experiment",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
    apple: '/favicon.png',
    shortcut: '/favicon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" sizes="any" />
      </head>
      <Loader />
      {/* <Token3d /> */}
      <LenisSmoothScroll />
      <body
        className={`${Font1.variable} ${Font2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
